# Generated by Django 5.2.1 on 2025-06-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_venta_producto_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='Producto',
        ),
    ]
