# Generated by Django 5.2.1 on 2025-05-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='rol',
        ),
    ]
